name: Validate JSON

on:
  pull_request:
    paths:
      - '**/*.json'
      - '.github/workflows/*.yml'

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Validate any changed json files
        run: |
          echo "Validating json files..."
          find . -type f -name "*.json" ! -path "./node_modules/*" -print0 | \
            xargs -0 -n1 jq empty
